x <- rnorm(100)
hist(x)
y <- rnorm(100)
plot(x, y)
par(mar = c(2, 2, 2, 2))
plot(x, y)
par(mar = c(4, 4, 2, 2))
plot(x, y)
plot(x, y, pch = 3)
example(points)

plot(x, y, pch = 20)
title('scatterplot')
text(-2, -2, 'label')
legend('topleft', legend = 'data', pch = 20)
fit <- lm(y ~ x)
abline(fit)
abline(fit, lwd = 3)
abline(fit, lwd = 3, col = 'blue')

plot(x, y, xlab = 'weight', ylab = 'height', main = 'scatterplot', pch = 20)
legend('topright', legend = 'Data', pch = 20)
fit <- lm(y ~ x)
abline(fit, lwd = 3, col = 'red')

# multiple plots
z <- rpois(100, 2)
par(mfrow = c(2, 1))
plot(x, y, pch = 20)
plot(x, z, pch = 19)
par('mar')
par(mar = c(2, 2, 1, 1))
plot(x, y, pch = 20)
plot(x, z, pch = 19)
par(mfrow = c(1, 2))
plot(x, y, pch = 20)
plot(x, z, pch = 19)
par(mar = c(4, 4, 2, 2))
plot(x, y, pch = 20)
plot(x, z, pch = 19)
par(mfrow = c(2, 2))
plot(x, y)
plot(x, z)
plot(z, x)
plot(y, x)
par(mfcol = c(2, 2))
plot(x, y)
plot(x, z)
plot(z, x)
plot(y, x)

par(mfrow = c(1, 1))
x <- rnorm(100)
y <- x + rnorm(100)
g <- gl(2, 50)
g <- gl(2, 50, labels = c("male", "female"))
str(g)
plot(x, y)
plot(x, y, type = 'n')
points(x[g == "male"], y[g == 'male'], col = 'green')
points(x[g == "female"], y[g == 'female'], col = 'red', pch = 19)
